[tool.poetry]
name = "backend"
version = "0.1.0"
description = "Your FastAPI Backend"

[tool.pytest.ini_options]
pythonpath = [
    "."
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api" 